// Template 2

#pragma GCC optimize("Ofast")
#pragma GCC optimization("unroll-loops")
#include <bits/stdc++.h>
using namespace std;
#define gc getchar_unlocked
#define fo(i, n) for (i = 0; i < n; i++)
#define ll long long int
#define double long double
#define si(x) scanf("%d", &x)
#define sl(x) scanf("%lld", &x)
#define ss(s) scanf("%s", s)
#define pi(x) printf("%d", x)
#define pl(x) printf("%lld", x)
#define ps(s) printf("%s", s)
#define pb push_back
#define pf push_front
#define mp make_pair
#define el "\n"
#define ell cout << el
#define F first
#define S second
#define all(x) x.begin(), x.end()
#define sortall(x) sort(all(x))
#define sortrev(x) sort(x.rbegin(), x.rend())
#define tr(it, a) for (auto it = a.begin(); it != a.end(); it++)
#define dbg(x) cout << #x << " == " << x << "\n";
#define cina(arr)              \
    for (ll i = 0; i < n; ++i) \
        cin >> arr[i];
#define couta(arr)             \
    for (ll i = 0; i < n; ++i) \
        cout << arr[i] << " "; \
    cout << "\n";
typedef pair<int, int> pii;
typedef pair<ll, ll> pl;
typedef vector<int> vi;
typedef vector<string> vs;
typedef vector<ll> vl;
typedef vector<pii> vpii;
typedef vector<pl> vpl;
typedef vector<vi> vvi;
typedef vector<vl> vvl;
typedef set<ll> sl;
typedef multiset<ll> msl;
typedef map<int, int> mii;
typedef map<ll, ll> ml;
const long long int MOD = 1e9 + 7;

void solve()
{
}

int main()
{
    //freopen(".in","r",stdin);
    //freopen(".out","w",stdout);
    ios_base::sync_with_stdio(false);
    cin.tie(NULL);
    cout.tie(NULL);
    ll t;
    cin >> t;
    while (t--)
        solve();
    return 0;
}
